apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-secret
type: Opaque
stringData:
  RCLONE_CONFIG_GS_TYPE: google cloud storage
  RCLONE_CONFIG_GS_ANONYMOUS: "false"
  RCLONE_CONFIG_GS_SERVICE_ACCOUNT_CREDENTIALS: '...'